### ISSUE TITLE
Q: blobs

### ISSUE THREAD

**Issue by glycerine** [tidwall/summitdb#8]
> Everything a string - SummitDB stores only strings which are exact binary representations of what the user stores.

I'm not that familiar with the redis protocol... how do I store a binary blob of []byte data that isn't necessarily even utf8? -- would I need to encode it first, for example using base64? Ugh, I'm hoping not!

Thanks for this terrific looking project. The raft and fencing tokens in particular mean I might be able to avoid deploying zookeeper. (happiness!)

**Comment by glycerine** [comment]
Ah. https://redis.io/topics/protocol says that RESP bulk strings are binary safe.

> RESP Bulk Strings
>
>Bulk Strings are used in order to represent a single binary safe string up to 512 MB in length.
>
>Bulk Strings are encoded in the following way:
>
>    * A "$" byte followed by the number of bytes composing the string (a prefixed length), terminated by CRLF.
>    * The actual string data.
>    * A final CRLF.
>
>So the string "foobar" is encoded as follows:
>
>"$6\r\nfoobar\r\n"

Is this (RESP bulk string) what SummitDB stores?

**Comment by tidwall** [comment]
> Is this (RESP bulk string) what SummitDB stores?

Yes. Summit store the bulk string in a similar manner as Redis. So you can store utf8, utf16, ascii, or a jpeg... and get that same object back.

The description in the README file poorly written, sorry about that.

> The raft and fencing tokens in particular mean I might be able to avoid deploying zookeeper. (happiness!)

Happiness indeed. This is specifically to address the issues with the [Redlock pattern](https://martin.kleppmann.com/2016/02/08/how-to-do-distributed-locking.html). It's my favorite feature because I can create a super lightweight and consistent distributed locking machine on AWS with only 3 nano instances.

**Comment by glycerine** [comment]
> I can create a super lightweight and consistent distributed locking machine on AWS with only 3 nano instances.

NICE!! Just curious though, how do you do that without being able to read without changing the FENCE value (ala #10 ) ?

**Comment by tidwall** [comment]
I've been using the fencing token for something I call Priority Fencing which allows for distributing key/value pairs across multiple servers. It's a scatter gather model where duplicate keys may exists on multiple servers, but never a duplicate Priority.

I use to use a timestamp (but clock drift made me nervous), then I tried Redlock, now I'm trying this.
